joyrex2001/kubedock

- Dockerfile
The busybox image does not contain public CA certs. When test-containers tries
to ping the container registry via containerized kubedock we get an error:
"x509: certificate signed by unknown authority"
Using a minimal Alpine image with the public CAs resolves this issue.
> Include public CA certificates in container image

- cmd/server.go
- internal/backend/deploy.go
- internal/model/types/container.go
- internal/model/types/container_test.go
- internal/server/main.go
- internal/server/routes/containers.go
- internal/server/routes/main.go
- internal/server/routes/types.go
- Added a CLI flag that sets a default RunAsUser on managed pods, which
can be overridden by setting the User value when creating a container
via the Docker API.
- Implemented as a PodSecurityContext on the generated pod. This is
useful for running Kubedock against K8S clusters that require pods to
run as non-root
> Allow specifying the User a container should run as

- internal/backend/deploy.go
In some environments (like our overloaded EKS cluster) it might take more than the hardcoded 30 seconds timeout for the `setup` init container to start.
~~This change makes it configuration with a default 30s which should match the current behaviour if the parameter is not overwritten.~~
Simply use the `timeout` configuration parameter for the init timeout instead of the hardcoded 30s
> Use timeout config for the init container timeout

- .gitignore
- Dockerfile
- internal/model/types/container.go
- internal/model/types/container_test.go
This is to handle the scenario where an environment variable's value legitimately contains an equals character
> ISSUE-25: Splits env variable string on first occurrence of equals character

- internal/backend/copy.go
- internal/backend/main.go
- internal/server/routes/common/archive.go
I've added a method for checking if file exists on pod before executing other command that will fail if file does not exist. This way we can return 404 Not Found error if file does not exist instead of 500.
I've had a problem with running elasticsearch testcontainers, because their [error handling](https://github.com/testcontainers/testcontainers-java/blob/d80ce6043fa4c4220532567490433d7824a2e77b/modules/elasticsearch/src/main/java/org/testcontainers/elasticsearch/ElasticsearchContainer.java#L142) only checks for 404 and not for 500. 
I've tested this with custom integration tests: [docker_test.zip](https://github.com/joyrex2001/kubedock/files/13363103/docker_test.zip).
> Return 404 if file does not exist on pod

- Makefile
I've had to figure out the dependencies needed for local development so I thought I would add them to the `README.md` to make it easier for contributing. I listed the dependencies I needed to install before I could run kubedock via `make run` command.
> Add development notes to README.md

- internal/backend/deploy.go
- internal/backend/logs.go
- internal/backend/logs_test.go
- internal/backend/main.go
- internal/server/routes/common/containers.go
- internal/server/routes/common/logs.go
This PR implements the `since` and `timestamps` query parameters.
I have left the `until` not implemented, because the API version that the kubedoc reports does not support it, and also because that would require manual filtering of the logs, as the underlaying k8s API does not support it either.
This PR makes kubedoc to support  this kind of use cases:
```
❯ DOCKER_HOST=localhost:2475 docker logs ea7cfd449f27 --timestamps --since=15s -n3
2023-12-21T14:41:16.669501622Z ok
2023-12-21T14:41:17.169580367Z ok
2023-12-21T14:41:17.669646665Z ok
```
> Implement support for timestamps and since

- internal/backend/deploy.go
- internal/backend/logs.go
- internal/server/routes/common/containers.go
- internal/server/routes/common/logs.go
This PR changes the type used the tail limit, so that negative numbers are treated as no limit, instead of crashing.
This hopefully fixes an issue reported here: https://github.com/joyrex2001/kubedock/issues/77
> Fix tailing logs with negative limits

- internal/backend/deploy.go
- internal/backend/deploy_test.go
- internal/model/types/container.go
This pr does the following:
- Fixes https://github.com/joyrex2001/kubedock/issues/89
- Splits the `addVolumes` function into two functions `addVolumes` and `addPreArchives` to clearly separate the two functionalities
- Splits the tests as well and adds a new test with the combination of `addVolumes` and `addPreArchives`
> Copy pre-archived files if there are any 

- internal/backend/deploy_test.go
This fixes the test of my last pull request. I was playing around with calling `kub.addPreArchives(tst.in, pod)` before and after `kub.addVolumes(tst.in, pod)` to see if it makes a difference. It does not, but then I forgot to add the call `kub.addPreArchives(tst.in, pod)` altogether (which is of course needed to test the combination) and forgot to run the tests again🙈.
Sorry about that. Fortunately, the CI runs the tests again to catch exactly such errors of my own laziness.
> Fix Add Volumes and Pre Archives Test

- internal/backend/deploy.go
- internal/model/types/container.go
- internal/server/routes/docker/containers.go
- internal/server/routes/docker/types.go
1. when a hostname is specified, kubedock should also create a service for that hostname
2. when a hostname is specified, the pod definition now has pod.spec.hostname set to the hostname.
3. dealing with duplicates in aliases and hostname and also converting the hostname and aliases to lower case
> fix: honor hostname setting in containers

- go.mod
- go.sum
- internal/util/tar/concatreader.go
- internal/util/tar/concatreader_test.go
- internal/util/tar/reader.go
- internal/util/tar/reader_test.go
- internal/util/tar/tar.go
Previously, the PutContainerArchive handler only supported uncompressed tar archives. This PR adds support for gzip, xz, and bzip2 compressed archives.
> Support compressed tar at PutContainerArchive operation

- cmd/server.go
- internal/backend/deploy.go
- internal/backend/main.go
- internal/main.go
Fixes #110
This patch adds a --disable-services command-line flag to disable the creation of services. Together with the added annotations, this allows kubedock-dns to be used to run multiple test jobs at the same time in a single namespace.
> issue-110 Optional disabling of services to allow network flattening

- internal/util/ioproxy/ioproxy.go
Current implementation outputs only lines with newline.
It outputs last line without newline as output of following command.
```bash
$ podman exec -i 02d121024407 /bin/sh
echo "line1
line2
line3"
line1
line2
echo echo2
line3
echo echo3
echo2
```
For first `echo` it outputs only two lines. 
It outputs third line after second `echo`
> Improve stdout for multiline without newline

- internal/util/ioproxy/ioproxy.go
Fixed #117 partly reverts an earlier fix. There was an error in ioproxy that never wrote the final line completely. With this fix, the previous fix for #117 is not needed anymore and the same issue is fixed in a more clean way.
> Last line was never written completely in ioproxy.process()

- internal/model/types/container.go
This PR handles the issue mentioned in https://github.com/joyrex2001/kubedock/issues/119 
The issue happens when the following `cmd.withUser("root")` is set in TestContainers.
> root user id is always 0 add handling when runAs is set to "root"

- internal/backend/deploy.go
I'm using @ErikEngerd's `kubedock-dns` and `--disable-services` 
When starting containers with `kubedock.hostalias/0` that are empty the container will fail to start (prob due to the mutating webhook if I understand it correctly)
I think it makes sense to set kubedock.hostalias/0 to the pod's name when its not set by any other means.
Let me know if this is a good fix or if you have any other suggestions.
Thanks.
-DM
> set kubedock.hostalias/0 to pod name rather than leaving it empty

- internal/backend/deploy.go
- internal/model/types/container.go
- internal/model/types/file.go
- internal/util/tar/tar.go
- internal/util/tar/tar_test.go
This is a work in progress PR that refactor the code to use allow for indevidual file permissions by using indevidual items in the config map.
@joyrex2001 I'm still relatively new to GO and would appreciate any feedback and code review.
Also I'm still trying to figure out how to to determine the original file permissions in the contest of `addPreArchives` any point in the right direction would be appriciated.
P.S - I will remove WIP from this PR when I feel like it is ready to be merged.
-DM
> Feature - Preserve original pre archive file permissions

- internal/backend/deploy.go
Hi,
as discussed in https://github.com/joyrex2001/kubedock/issues/129, this is the PR for the fix.
Regards,
Daniel
> re-use resource requests/limits for setupInitContainer

- internal/server/routes/docker/containers.go
- internal/server/routes/docker/types.go
Hi Everyone, 
As specified in issue https://github.com/joyrex2001/kubedock/issues/131 when a specific network is specified KubeDock doesnt assign the container to the specified network.
This fix aim to resolve this issue.
Based on my testing containers where a network is not specified are handled as before and when a network is specified the containers are assigned to the specified network 
As always code review and feedback would be much appreciated.
Thank you.
-DM
> Fix Network Assignment

- internal/server/routes/docker/containers.go
The docker api allows the usage of Network Name or Network ID so this PR fixes my earlier PR that only allows the usage of Network Name.
I apologize for the PR duplication.
Thanks.
-DM
> Allows Network Assignment by NetworkName or NetworkID
